set(_AMENT_PACKAGE_NAME "linrob_axis")
set(linrob_axis_VERSION "0.1.2")
set(linrob_axis_MAINTAINER "Matomai <info@matom.ai>")
set(linrob_axis_BUILD_DEPENDS "ros2_control" "hardware_interface" "rosidl_default_generators" "rclcpp" "std_msgs" "controller_interface" "pluginlib")
set(linrob_axis_BUILDTOOL_DEPENDS "ament_cmake")
set(linrob_axis_BUILD_EXPORT_DEPENDS "rclcpp" "std_msgs" "controller_interface" "pluginlib")
set(linrob_axis_BUILDTOOL_EXPORT_DEPENDS )
set(linrob_axis_EXEC_DEPENDS "ros2_control" "hardware_interface" "rosidl_default_runtime" "rclcpp" "std_msgs" "controller_interface" "pluginlib")
set(linrob_axis_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(linrob_axis_GROUP_DEPENDS )
set(linrob_axis_MEMBER_OF_GROUPS "rosidl_interface_packages")
set(linrob_axis_DEPRECATED "")
set(linrob_axis_EXPORT_TAGS)
list(APPEND linrob_axis_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
list(APPEND linrob_axis_EXPORT_TAGS "<hardware_interface_plugin>resource_plugin.xml</hardware_interface_plugin>")
list(APPEND linrob_axis_EXPORT_TAGS "<controller_interface_plugin>controller_plugin.xml</controller_interface_plugin>")
