name: ros2-linrob
version: "0.1.1"
summary: Snap with ROS 2 controllers and resource for linrob hardware.
description: |
  This snap contains the ROS 2 controllers and resources for the linrob hardware.
  It is designed to be used with the ctrlX CORE platform.

base: core22
grade: stable
confinement: strict

parts:
  ros-app:
    plugin: dump
    source: install
    stage-packages:
      - ros-humble-xacro
      - libzmq5
      - ctrlx-datalayer
    override-build: |
      snapcraftctl build

  wrapper-scripts:
    plugin: dump
    source: wrapper/
    organize:
      ./run-position-controller.sh: usr/bin/run-position-controller

apps:
  position-controller:
    command: usr/bin/run-position-controller
    plugs:
      - ros-base
      - network
      - network-bind
    daemon: simple
    passthrough:
      restart-condition: always
      restart-delay: 10s

plugs:
  ros-base:
    interface: content
    content: executables
    target: $SNAP/rosruntime

  datalayer:
    interface: content
    content: datalayer
    target: $SNAP_DATA/.datalayer
