controller_manager:
  ros__parameters:
    update_rate: 500

    hardware_components_initial_state:
      inactive:
        - linrob_hw

    position_controller:
      type: position_controllers/JointGroupPositionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

position_controller:
  state: inactive
  ros__parameters:
    joints:
      - joint_1

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity
