controller_manager:
  ros__parameters:
    update_rate: 500

    position_controller:
      type: position_controllers/JointGroupPositionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    axis_controller:
      type: linrob_controllers/AxisController

position_controller:
  ros__parameters:
    state: inactive
    joints:
      - joint_1

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

axis_controller:
  ros__parameters:
    state: inactive
    joints:
      - joint_1
