controller_manager:
  ros__parameters:
    update_rate: 500

    client_position_controller:
      type: position_controllers/JointGroupPositionController

client_position_controller:
  ros__parameters:
    joints:
      - joint_1

    command_interfaces:
      - position

    state_interfaces:
      - position

    input_topic: /client_position_command
