name: Build ARM64 Debian

on:
  push:
    tags:
      - 'v*'      # build on new version tags
    branches:
      - main      # optionally also on main pushes

jobs:
  build-arm64:
    runs-on: ubuntu-22.04-arm

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update

          # Install core build tools and rosdep
          sudo apt-get install -y \
            build-essential \
            fakeroot \
            dpkg-dev \
            python3-rosdep2 \
            git

          # Install Python dependencies separately from system dependencies
          sudo python3 -m pip install -U pip setuptools colcon-common-extensions bloom

          # Initialize and update rosdep
          sudo rosdep init || true
          rosdep update

          # Install ROS dependencies using rosdep, which automatically finds and installs all
          # required packages listed in your package.xml files. This is the most reliable method.
          rosdep install --from-paths ros2_ws/src --ignore-src --rosdistro humble -y

      - name: Build ROS2 package
        run: |
          cd ros2_ws
          colcon build --merge-install

      - name: Generate Debian package
        run: |
          # Use bloom to generate the debian files and fakeroot to build the package.
          # The package.xml file should be located at ros2_ws/src/linrob_axis/package.xml
          cd ros2_ws/src/linrob_axis
          bloom-generate rosdebian --os-name ubuntu --os-version 22.04 --ros-distro humble
          fakeroot debian/rules binary

      - name: Upload ARM64 DEB
        uses: actions/upload-artifact@v4
        with:
          name: linrob_axis-deb-arm64
          path: ros2_ws/src/linrob_axis/*.deb
