name: Build ROS 2 Debian Package for ARM

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Setup ROS 2
      uses: ros-tooling/setup-ros@v0.7
      with:
        required-ros-distributions: humble

    - name: Set up ROS 2 apt repo
      run: |
        sudo apt update
        sudo apt install -y curl gnupg2 lsb-release software-properties-common
        sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key \
          -o /usr/share/keyrings/ros-archive-keyring.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" \
          | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null
        sudo apt update

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          python3-bloom \
          python3-rosdep \
          fakeroot \
          devscripts \
          dpkg-cross \
          qemu-user-static \
          binfmt-support \
          debootstrap \
          sbuild

    - name: Install build tools & ROS dependencies
        run: |
          sudo apt install -y \
            build-essential devscripts debhelper dh-make \
            gcc-aarch64-linux-gnu g++-aarch64-linux-gnu \
            ros-humble-ament-cmake \
            ros-humble-ament-lint-auto \
            ros-humble-ament-lint-common \
            ros-humble-controller-interface \
            ros-humble-hardware-interface \
            ros-humble-pluginlib \
            ros-humble-rclcpp \
            ros-humble-ros2-control \
            ros-humble-rosidl-default-generators \
            ros-humble-std-msgs

    - name: Build Debian package (for ARM)
      run: |
        cd ros2_ws/src/linrob_axis
        sudo apt install -y debhelper devscripts fakeroot
        export CC=aarch64-linux-gnu-gcc
        export CXX=aarch64-linux-gnu-g++
        debuild -us -uc -b -aarm64

    - name: Upload Debian package
      uses: actions/upload-artifact@v4
      with:
        name: ros2-aarm64-deb
        path: ~/ros2_ws/src/*.deb
