name: Build Debian Packages (amd64 + arm64)

on:
  push:
    tags:
      - 'v*'  # e.g., v1.0.0

jobs:
  build-deb:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        arch: [amd64, arm64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up architecture
        run: |
          if [ "${{ matrix.arch }}" = "arm64" ]; then
            sudo dpkg --add-architecture arm64
            # Replace all default Ubuntu repos for arm64 with ports.ubuntu.com
            sudo sed -i -e 's|http://archive.ubuntu.com/ubuntu/|http://ports.ubuntu.com/ubuntu-ports/|g' /etc/apt/sources.list
            sudo sed -i -e 's|http://security.ubuntu.com/ubuntu|http://ports.ubuntu.com/ubuntu-ports|g' /etc/apt/sources.list

            # Ensure backports, updates, and security all point to ports
            sudo sed -i -e 's|jammy-updates|jammy-updates|g' /etc/apt/sources.list
            sudo sed -i -e 's|jammy-backports|jammy-backports|g' /etc/apt/sources.list
            sudo sed -i -e 's|jammy-security|jammy-security|g' /etc/apt/sources.list
          fi
          sudo apt-get update

      - name: Install build dependencies
        run: |
          # Host packages
          sudo apt-get install -y \
            build-essential \
            fakeroot \
            dpkg-dev \
            python3-rosdep \
            python3-colcon-common-extensions \
            qemu-user-static

          # Only arm64 cross-build packages
          if [ "${{ matrix.arch }}" = "arm64" ]; then
            sudo apt-get install -y crossbuild-essential-arm64
          fi

      - name: Initialize rosdep
        run: |
          sudo rosdep init || true
          rosdep update

      - name: Install ROS 2 dependencies
        run: |
          rosdep install --from-paths . --ignore-src -y --rosdistro humble --os=ubuntu:jammy

      - name: Build Debian package
        run: |
          export DEB_BUILD_OPTIONS="parallel=$(nproc)"
          if [ "${{ matrix.arch }}" = "amd64" ]; then
            dpkg-buildpackage -us -uc -a amd64
          else
            dpkg-buildpackage -us -uc -a arm64
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: debian-package-${{ matrix.arch }}
          path: ../*.deb
