name: Build ARM64 Debian

on:
  push:
    tags:
      - 'v*'        # build on new version tags
    branches:
      - main        # optionally also on main pushes

jobs:
  build-arm64:
    runs-on: ubuntu-22.04-arm

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python-pip
            build-essential \
            fakeroot \
            dpkg-dev \
            python3-rosdep2 \
            git
            
          sudo pip install colcon-common-extensions

      - name: Initialize rosdep
        run: |
          sudo rosdep init || true
          rosdep update

      - name: Setup ROS2 environment
        run: |
          sudo apt-get install -y curl gnupg2 lsb-release
          sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -
          sudo sh -c 'echo "deb http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" > /etc/apt/sources.list.d/ros2.list'
          sudo apt-get update
          sudo apt-get install -y ros-humble-desktop

      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip setuptools
          pip3 install -U colcon-common-extensions bloom

      - name: Build ROS2 package
        run: |
          cd ros2_ws
          colcon build --merge-install
          source install/setup.bash

      - name: Generate Debian package
        run: |
          cd ros2_ws/src/linrob_axis
          bloom-generate rosdebian --os-name ubuntu --os-version 22.04 --ros-distro humble
          fakeroot debian/rules binary

      - name: Upload ARM64 DEB
        uses: actions/upload-artifact@v4
        with:
          name: linrob_axis-deb-arm64
          path: ros2_ws/src/linrob_axis/*.deb
