name: Build ROS 2 Debian Package for ARM

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Setup ROS 2
      uses: ros-tooling/setup-ros@v0.7
      with:
        required-ros-distributions: humble

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          python3-bloom \
          python3-rosdep \
          fakeroot \
          devscripts \
          dpkg-cross \
          qemu-user-static \
          binfmt-support \
          debootstrap \
          sbuild

    - name: Build Debian package (for ARM)
      run: |
        cd ros2_ws/src/linrob_axis
        dpkg-buildpackage -b -aarmhf

    - name: Upload Debian package
      uses: actions/upload-artifact@v4
      with:
        name: ros2-armhf-deb
        path: ~/ros2_ws/src/*.deb
