name: Build arm64 Debian Package

on:
  push:
    tags:
      - 'v*'   # e.g. v1.0.0

jobs:
  build-deb:
    runs-on: ubuntu-22.04-arm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Enable arm64 architecture
        run: |

          sudo apt-get update

      - name: Install cross-build dependencies
        run: |
          sudo apt-get install -y \
            build-essential \

            fakeroot \
            dpkg-dev \

            python3-rosdep \
            python3-colcon-common-extensions

      - name: Initialize rosdep
        run: |
          sudo rosdep init || true
          rosdep update

      - name: Install ROS 2 dependencies for Humble (arm64)
        run: |
          rosdep install --from-paths . --ignore-src -y --rosdistro humble --os=ubuntu:jammy

      - name: Build Debian package
        run: |
          # Build in source since bloom already created debian/ folder
          export DEB_BUILD_OPTIONS="parallel=$(nproc)"
          dpkg-buildpackage -us -uc -a arm64

      - name: Upload .deb artifact
        uses: actions/upload-artifact@v4
        with:
          name: debian-package-arm64
          path: ../*.deb
